#MODEL_ID=0 make run platform=gvsoc > output.txt

START_MODEL=0
STOP_MODEL=32
mkdir -p logs/


##########################################
FREQ_FC=250000000
FREQ_CL=175000000
MODEL_L2_MEMORY=250000
MODEL_L1_MEMORY=48804
#12 Volt

for MODEL_L2_MEMORY in 350000 300000 250000 200000 325000 225000; do
	
	FREQ_FC=250000000
	FREQ_CL=175000000
	for i in `seq $START_MODEL $STOP_MODEL`;
	do
		MODEL_ID=$i FREQ_CL=$FREQ_CL FREQ_FC=$FREQ_FC MODEL_L2_MEMORY=$MODEL_L2_MEMORY make clean model  > new\_logs/atmodel\_$i\_12\_$FREQ_CL\_$FREQ_FC\_$MODEL_L2_MEMORY\_$MODEL_L1_MEMORY.txt
		MODEL_ID=$i FREQ_CL=$FREQ_CL FREQ_FC=$FREQ_FC MODEL_L2_MEMORY=$MODEL_L2_MEMORY make all 
		python3 ps4444Measure.py new\_logs/power\_$i\_12\_$FREQ_CL\_$FREQ_FC\_$MODEL_L2_MEMORY\_$MODEL_L1_MEMORY & 
		MODEL_ID=$i FREQ_CL=$FREQ_CL FREQ_FC=$FREQ_FC MODEL_L2_MEMORY=$MODEL_L2_MEMORY make run > new\_logs/output\_board\_log\_$i\_12\_$FREQ_CL\_$FREQ_FC\_$MODEL_L2_MEMORY\_$MODEL_L1_MEMORY.txt
	done 

#	FREQ_FC=250000000
#	FREQ_CL=175000000
#	for i in `seq $START_MODEL $STOP_MODEL`;
#	do
#		MODEL_ID=$i FREQ_CL=$FREQ_CL FREQ_FC=$FREQ_FC MODEL_L2_MEMORY=$MODEL_L2_MEMORY make clean model  > new\_logs/atmodel\_$i\_$FREQ_CL\_$FREQ_FC\_$MODEL_L2_MEMORY\_$MODEL_L1_MEMORY.txt
#		MODEL_ID=$i FREQ_CL=$FREQ_CL FREQ_FC=$FREQ_FC MODEL_L2_MEMORY=$MODEL_L2_MEMORY make all 
#		python3 ps4444Measure.py new\_logs/power\_$i\_$FREQ_CL\_$FREQ_FC\_$MODEL_L2_MEMORY\_$MODEL_L1_MEMORY & 
#		MODEL_ID=$i FREQ_CL=$FREQ_CL FREQ_FC=$FREQ_FC MODEL_L2_MEMORY=$MODEL_L2_MEMORY make run > new\_logs/output\_board\_log\_$i\_$FREQ_CL\_$FREQ_FC\_$MODEL_L2_MEMORY\_$MODEL_L1_MEMORY.txt
#	done 

done



#for i in `seq 16 $NUM_MODELS`;
#do
#	MODEL_ID=$i FREQ_CL=$FREQ_CL FREQ_FC=$FREQ_FC MODEL_L2_MEMORY=$MODEL_L2_MEMORY make clean all 
#	MODEL_ID=$i FREQ_CL=$FREQ_CL FREQ_FC=$FREQ_FC MODEL_L2_MEMORY=$MODEL_L2_MEMORY make run > logs/output\_board\_log\_$i\_$FREQ_CL\_$FREQ_FC\_$MODEL_L2_MEMORY\_$MODEL_L1_MEMORY.txt
#done  
#
#FREQ_FC=250000000
#FREQ_CL=50000000
#
#for i in `seq 16 $NUM_MODELS`;
#do
#	MODEL_ID=$i FREQ_CL=$FREQ_CL FREQ_FC=$FREQ_FC MODEL_L2_MEMORY=$MODEL_L2_MEMORY make clean all 
#	MODEL_ID=$i FREQ_CL=$FREQ_CL FREQ_FC=$FREQ_FC MODEL_L2_MEMORY=$MODEL_L2_MEMORY make run > logs/output\_board\_log\_$i\_$FREQ_CL\_$FREQ_FC\_$MODEL_L2_MEMORY\_$MODEL_L1_MEMORY.txt
#done  



#FREQ_FC=250000000
#FREQ_CL=175000000
#MODEL_L2_MEMORY=200000
#MODEL_L1_MEMORY=48804
#
##for i in `seq 0 $NUM_MODELS`;
##do
##	MODEL_ID=$i FREQ_CL=$FREQ_CL FREQ_FC=$FREQ_FC MODEL_L2_MEMORY=$MODEL_L2_MEMORY make clean all platform=gvsoc
##	MODEL_ID=$i FREQ_CL=$FREQ_CL FREQ_FC=$FREQ_FC MODEL_L2_MEMORY=$MODEL_L2_MEMORY make run platform=gvsoc > logs/output\_log\_$i\_$FREQ_CL\_$FREQ_FC\_$MODEL_L2_MEMORY\_$MODEL_L1_MEMORY.txt
##done    
#
#for i in `seq 16 $NUM_MODELS`;
#do
#	MODEL_ID=$i FREQ_CL=$FREQ_CL FREQ_FC=$FREQ_FC MODEL_L2_MEMORY=$MODEL_L2_MEMORY make clean all 
#	MODEL_ID=$i FREQ_CL=$FREQ_CL FREQ_FC=$FREQ_FC MODEL_L2_MEMORY=$MODEL_L2_MEMORY make run > logs/output\_board\_log\_$i\_$FREQ_CL\_$FREQ_FC\_$MODEL_L2_MEMORY\_$MODEL_L1_MEMORY.txt
#done  
#
#
#FREQ_FC=250000000
#FREQ_CL=50000000
##for i in `seq 0 $NUM_MODELS`;
##do
##	MODEL_ID=$i FREQ_CL=$FREQ_CL FREQ_FC=$FREQ_FC MODEL_L2_MEMORY=$MODEL_L2_MEMORY make clean all platform=gvsoc
##	MODEL_ID=$i FREQ_CL=$FREQ_CL FREQ_FC=$FREQ_FC MODEL_L2_MEMORY=$MODEL_L2_MEMORY make run platform=gvsoc > logs/output\_log\_$i\_$FREQ_CL\_$FREQ_FC\_$MODEL_L2_MEMORY\_$MODEL_L1_MEMORY.txt
##done  
#
#for i in `seq 16 $NUM_MODELS`;
#do
#	MODEL_ID=$i FREQ_CL=$FREQ_CL FREQ_FC=$FREQ_FC MODEL_L2_MEMORY=$MODEL_L2_MEMORY make clean all 
#	MODEL_ID=$i FREQ_CL=$FREQ_CL FREQ_FC=$FREQ_FC MODEL_L2_MEMORY=$MODEL_L2_MEMORY make run > logs/output\_board\_log\_$i\_$FREQ_CL\_$FREQ_FC\_$MODEL_L2_MEMORY\_$MODEL_L1_MEMORY.txt
#done  
#
#FREQ_FC=250000000
#FREQ_CL=175000000
#MODEL_L2_MEMORY=250000
#MODEL_L1_MEMORY=48804
#
#for i in `seq 16 $NUM_MODELS`;
#do
#	MODEL_ID=$i FREQ_CL=$FREQ_CL FREQ_FC=$FREQ_FC MODEL_L2_MEMORY=$MODEL_L2_MEMORY make clean all 
#	MODEL_ID=$i FREQ_CL=$FREQ_CL FREQ_FC=$FREQ_FC MODEL_L2_MEMORY=$MODEL_L2_MEMORY make run > logs/output\_board\_log\_$i\_$FREQ_CL\_$FREQ_FC\_$MODEL_L2_MEMORY\_$MODEL_L1_MEMORY.txt
#done  
#
#FREQ_FC=250000000
#FREQ_CL=50000000
#
#for i in `seq 16 $NUM_MODELS`;
#do
#	MODEL_ID=$i FREQ_CL=$FREQ_CL FREQ_FC=$FREQ_FC MODEL_L2_MEMORY=$MODEL_L2_MEMORY make clean all 
#	MODEL_ID=$i FREQ_CL=$FREQ_CL FREQ_FC=$FREQ_FC MODEL_L2_MEMORY=$MODEL_L2_MEMORY make run > logs/output\_board\_log\_$i\_$FREQ_CL\_$FREQ_FC\_$MODEL_L2_MEMORY\_$MODEL_L1_MEMORY.txt
#done  
#######################################
#FREQ_FC=250000000
#FREQ_CL=175000000
#MODEL_L2_MEMORY=300000
#MODEL_L1_MEMORY=48804
#
#for i in `seq 16 $NUM_MODELS`;
#do
#	MODEL_ID=$i FREQ_CL=$FREQ_CL FREQ_FC=$FREQ_FC MODEL_L2_MEMORY=$MODEL_L2_MEMORY make clean all 
#	MODEL_ID=$i FREQ_CL=$FREQ_CL FREQ_FC=$FREQ_FC MODEL_L2_MEMORY=$MODEL_L2_MEMORY make run > logs/output\_board\_log\_$i\_$FREQ_CL\_$FREQ_FC\_$MODEL_L2_MEMORY\_$MODEL_L1_MEMORY.txt
#done  
#
#FREQ_FC=250000000
#FREQ_CL=50000000
#
#for i in `seq 16 $NUM_MODELS`;
#do
#	MODEL_ID=$i FREQ_CL=$FREQ_CL FREQ_FC=$FREQ_FC MODEL_L2_MEMORY=$MODEL_L2_MEMORY make clean all 
#	MODEL_ID=$i FREQ_CL=$FREQ_CL FREQ_FC=$FREQ_FC MODEL_L2_MEMORY=$MODEL_L2_MEMORY make run > logs/output\_board\_log\_$i\_$FREQ_CL\_$FREQ_FC\_$MODEL_L2_MEMORY\_$MODEL_L1_MEMORY.txt
#done  
###########################################
#FREQ_FC=250000000
#FREQ_CL=175000000
#MODEL_L2_MEMORY=350000
#MODEL_L1_MEMORY=48804
#
#for i in `seq 16 $NUM_MODELS`;
#do
#	MODEL_ID=$i FREQ_CL=$FREQ_CL FREQ_FC=$FREQ_FC MODEL_L2_MEMORY=$MODEL_L2_MEMORY make clean all 
#	MODEL_ID=$i FREQ_CL=$FREQ_CL FREQ_FC=$FREQ_FC MODEL_L2_MEMORY=$MODEL_L2_MEMORY make run > logs/output\_board\_log\_$i\_$FREQ_CL\_$FREQ_FC\_$MODEL_L2_MEMORY\_$MODEL_L1_MEMORY.txt
#done  
#
#FREQ_FC=250000000
#FREQ_CL=50000000
#
#for i in `seq 16 $NUM_MODELS`;
#do
#	MODEL_ID=$i FREQ_CL=$FREQ_CL FREQ_FC=$FREQ_FC MODEL_L2_MEMORY=$MODEL_L2_MEMORY make clean all 
#	MODEL_ID=$i FREQ_CL=$FREQ_CL FREQ_FC=$FREQ_FC MODEL_L2_MEMORY=$MODEL_L2_MEMORY make run > logs/output\_board\_log\_$i\_$FREQ_CL\_$FREQ_FC\_$MODEL_L2_MEMORY\_$MODEL_L1_MEMORY.txt
#done  
