# Copyright (C) 2017 GreenWaves Technologies
# All rights reserved.

# This software may be modified and distributed under the terms
# of the BSD license.  See the LICENSE file for details.

MODEL_SUFFIX?=

MODEL_PREFIX?=GapFlow

MODEL_PYTHON=python3

# Increase this to improve accuracy
TRAINING_EPOCHS?=1
MODEL_COMMON ?= common
MODEL_COMMON_INC ?= $(GAP_SDK_HOME)/libs/gap_lib/include
MODEL_COMMON_SRC ?= $(GAP_SDK_HOME)/libs/gap_lib/img_io
MODEL_COMMON_SRC_FILES ?= ImgIO.c
MODEL_COMMON_SRCS = $(realpath $(addprefix $(MODEL_COMMON_SRC)/,$(MODEL_COMMON_SRC_FILES)))
MODEL_HEADERS = $(MODEL_COMMON)/headers
MODEL_TRAIN = model/train.py
MODEL_BUILD = BUILD_MODEL$(MODEL_SUFFIX)
MODEL_TRAIN_BUILD = BUILD_TRAIN$(TRAIN_SUFFIX)
MODEL_H5 = $(MODEL_TRAIN_BUILD)/$(MODEL_PREFIX).h5

MODEL_TFLITE = $(MODEL_BUILD)/$(MODEL_PREFIX).tflite

TENSORS_DIR = $(MODEL_BUILD)/tensors
MODEL_TENSORS = $(MODEL_BUILD)/$(MODEL_PREFIX)_L3_Flash_Const.dat

MODEL_STATE = $(MODEL_BUILD)/$(MODEL_PREFIX).json
MODEL_SRC = $(MODEL_PREFIX)Model.c
MODEL_GEN = $(MODEL_BUILD)/$(MODEL_PREFIX)Kernels 
MODEL_GEN_C = $(addsuffix .c, $(MODEL_GEN))
MODEL_GEN_CLEAN = $(MODEL_GEN_C) $(addsuffix .h, $(MODEL_GEN))
MODEL_GEN_EXE = $(MODEL_BUILD)/GenTile

MODEL_GENFLAGS_EXTRA =

EXTRA_GENERATOR_SRC =

IMAGES = images
RM=rm -f

NNTOOL=nntool

NNTOOL_PATH = $(GAP_SDK_HOME)/tools/nntool/
NNTOOL_KERNEL_PATH = $(NNTOOL_PATH)/autotiler/kernels
NNTOOL_GENERATOR_PATH = $(NNTOOL_PATH)/autotiler/generators

MODEL_LIB_POW2 += $(TILER_CNN_KERNEL_PATH)/CNN_BiasReLULinear_BasicKernels.c
MODEL_LIB_POW2 += $(TILER_CNN_KERNEL_PATH)/CNN_Conv_BasicKernels.c
MODEL_LIB_POW2 += $(TILER_CNN_KERNEL_PATH)/CNN_Conv_DP_BasicKernels.c
MODEL_LIB_POW2 += $(TILER_CNN_KERNEL_PATH)/CNN_Conv_DW_BasicKernels.c
MODEL_LIB_POW2 += $(TILER_CNN_KERNEL_PATH)/CNN_Conv_DW_DP_BasicKernels.c
MODEL_LIB_POW2 += $(TILER_CNN_KERNEL_PATH)/CNN_Pooling_BasicKernels.c
MODEL_LIB_POW2 += $(TILER_CNN_KERNEL_PATH)/CNN_MatAlgebra.c
MODEL_LIB_POW2 += $(TILER_CNN_KERNEL_PATH)/CNN_SoftMax.c
MODEL_LIB_INCLUDE_POW2 = 
MODEL_GEN_POW2 += $(TILER_CNN_GENERATOR_PATH)/CNN_Generators.c
MODEL_GEN_INCLUDE_POW2 = 

MODEL_LIB_SQ8 += $(TILER_CNN_KERNEL_PATH_SQ8)/CNN_Activation_SQ8.c
MODEL_LIB_SQ8 += $(TILER_CNN_KERNEL_PATH_SQ8)/CNN_Bias_Linear_SQ8.c
MODEL_LIB_SQ8 += $(TILER_CNN_KERNEL_PATH_SQ8)/CNN_Conv_SQ8.c
MODEL_LIB_SQ8 += $(TILER_CNN_KERNEL_PATH_SQ8)/CNN_Pooling_SQ8.c
MODEL_LIB_SQ8 += $(TILER_CNN_KERNEL_PATH_SQ8)/CNN_Conv_DW_SQ8.c
MODEL_LIB_SQ8 += $(TILER_CNN_KERNEL_PATH_SQ8)/CNN_MatAlgebra_SQ8.c
MODEL_LIB_SQ8 += $(TILER_CNN_KERNEL_PATH_SQ8)/CNN_SoftMax_SQ8.c
MODEL_LIB_SQ8 += $(TILER_CNN_KERNEL_PATH_SQ8)/CNN_AT_Misc.c
MODEL_LIB_SQ8 += $(TILER_CNN_KERNEL_PATH_SQ8)/RNN_SQ8.c
MODEL_LIB_INCLUDE_SQ8 = -I$(TILER_CNN_KERNEL_PATH_SQ8)
MODEL_GEN_SQ8 += $(TILER_CNN_GENERATOR_PATH_SQ8)/CNN_Generators_SQ8.c
MODEL_GEN_SQ8 += $(TILER_CNN_GENERATOR_PATH_SQ8)/RNN_Generators_SQ8.c
MODEL_GEN_INCLUDE_SQ8 = -I$(TILER_CNN_GENERATOR_PATH_SQ8)

MODEL_LIB_NE16 += $(TILER_CNN_KERNEL_PATH_NE16)/CNN_BasicKernels_NE16.c $(TILER_CNN_KERNEL_PATH_NE16)/CNN_Activation_HWC_SQ8.c
MODEL_LIB_INCLUDE_NE16 = -I$(TILER_CNN_KERNEL_PATH_NE16)
MODEL_GEN_NE16 += $(TILER_CNN_GENERATOR_PATH_NE16)/CNN_Generators_NE16.c
MODEL_GEN_INCLUDE_NE16 = -I$(TILER_CNN_GENERATOR_PATH_NE16)

MODEL_SIZE_CFLAGS = -DAT_INPUT_HEIGHT=$(AT_INPUT_HEIGHT) -DAT_INPUT_WIDTH=$(AT_INPUT_WIDTH) -DAT_INPUT_COLORS=$(AT_INPUT_COLORS)

# Common Files for both quantization schemes
CNN_GEN = $(TILER_CNN_GENERATOR_PATH)/CNN_Generator_Util.c $(TILER_CNN_GENERATOR_PATH)/CNN_Copy_Generators.c $(TILER_CNN_GENERATOR_PATH)/SSD_Generators.c $(NNTOOL_GENERATOR_PATH)/nntool_extra_generators.c
CNN_GEN_INCLUDE = -I$(TILER_CNN_GENERATOR_PATH) -I$(NNTOOL_GENERATOR_PATH)
CNN_LIB = $(TILER_CNN_KERNEL_PATH)/CNN_CopyBasicKernels.c $(NNTOOL_KERNEL_PATH)/norm_transpose.c
CNN_LIB_INCLUDE = -I$(TILER_CNN_KERNEL_PATH) -I$(NNTOOL_KERNEL_PATH)

ifdef MODEL_SQ8
  CNN_GEN += $(MODEL_GEN_SQ8)
  CNN_GEN_INCLUDE += $(MODEL_GEN_INCLUDE_SQ8)
  CNN_LIB += $(MODEL_LIB_SQ8)
  CNN_LIB_INCLUDE += $(MODEL_LIB_INCLUDE_SQ8)
endif
ifdef MODEL_POW2
  CNN_GEN += $(MODEL_GEN_POW2)
  CNN_GEN_INCLUDE += $(MODEL_GEN_INCLUDE_POW2)
  CNN_LIB += $(MODEL_LIB_POW2)
  CNN_LIB_INCLUDE += $(MODEL_LIB_INCLUDE_POW2)
endif
ifeq ($(MODEL_NE16), 1)
	CNN_GEN += $(MODEL_GEN_NE16)
	CNN_GEN_INCLUDE += $(MODEL_GEN_INCLUDE_NE16)
	CNN_LIB += $(MODEL_LIB_NE16)
	CNN_LIB_INCLUDE += $(MODEL_LIB_INCLUDE_NE16)
endif
$(info GEN ... $(CNN_GEN))

