APP = test
APP_SRCS += main.c spi_wifi.c
#APP_SRCS += spi_master.c
APP_INC += . $(GAP_LIB_PATH)/include
APP_CFLAGS +=
APP_CFLAGS += -DJPEG_Q_90
APP_LDFLAGS += -g -lgaplib



include $(RULES_DIR)/pmsis_rules.mk
